### ISSUE TITLE
Builds but how do you control?

### ISSUE THREAD

**Issue by MikeyWetzel** [toolboc/NesVoxel#2]
The app builds and runs fine on Hololens, but I can't get off the start screen. I tried two things: (1) using an Xbox bluetooth controller connected to the Hololens, and (2) using the Windows 10 Hololens app to send keystrokes to the Hololens.

Are either of these intended to work?

Thanks.

**Comment by MikeyWetzel** [comment]
BTW, I saw your checkin comment claiming to add Xbox One S Controller support: toolboc committed on Sep 16, 2016 - Requires latest controller firmware

I checked my controller firmware and it's the latest. Per the Windows 10 Xbox Accessories app, it says my controller has "Firmware version: 3.1.1221.0 - No update available"

I can verify that my Xbox One S Controller (bluetooth) works with my Hololens because I can run the HoloHeli app, which not only uses the controller, but displays full controller output (presumably for debugging).

I'm stumped.

**Comment by MikeyWetzel** [comment]
I notice people pairing Xbox controllers with other devices (android and rasppi) are complaining that the latest update (3.1.1221.0) made some "fixes" that break those devices. These complaints are from 5-10 months ago, so it's possible (seems unlikely, though) that the NesVoxel code is having a similiar issue.

References:
https://www.reddit.com/r/xboxone/comments/5hq20j/xbox_one_s_controller_firmware_rollback/

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=187262

**Comment by MikeyWetzel** [comment]
Got it to work. I had to uncomment line 33 in VxlApp.cpp which says:
    inputState.refreshInput();

I think that line might have been commented out by mistake, part of removing some other code to pause the emulation.

**Comment by toolboc** [comment]
Interesting, thank you for detailing your steps.   

I would be happy to accept a PR for the change you had to make.

**Comment by MikeyWetzel** [comment]
I'm sorry but i don't know was a PR is. (A p-something request?)

It's just uncommenting that one line of code.

While your in the code, another suggestion is to re-activate the scaling feature. When I ran the app, the screen is huge and I have to stand about 20 feet away. :)

I look forward to other things you do with a Hololens. Cheers.
